version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker/dev/nginx
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    build:
      context: docker/dev/nginx
    volumes:
      - ./:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: docker/dev/php-fpm
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      DB_URL: webapp:${DATABASE_URL}
    volumes:
      - ./:/app

  api-php-cli:
    build:
      context: docker/dev/php-cli
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./:/app

  api-postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54322:5432"

volumes:
  api-postgres: